<?php
$fbcolorscheme	=	 Mage::getStoreConfig('facebooklike_options/all_settings/fbcolorscheme'); 

$fbappid		=	Mage::getStoreConfig('facebooklike_options/all_settings/fbappid');

$fblayout		=	Mage::getStoreConfig('facebooklike_options/all_settings/fblayout');

$fbface			=	Mage::getStoreConfig('facebooklike_options/all_settings/fbface');
	
$fblocale		= 	Mage::app()->getLocale()->getLocaleCode();

$dbdatawidth	=	Mage::getStoreConfig('facebooklike_options/all_settings/datawidth');

if($fbface==1){

    $fbface='true';
	
    }else{

    $fbface='false';

}
$fbappid=($fbappid=='')	?	'512993528731249' : $fbappid	;//If FB APP ID is not added
$dbdatawidth=($dbdatawidth=='')	?	'450' : $dbdatawidth	;//default button width
?>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=<?php echo $fbappid;?>";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>
<div id="fb-root"></div><script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script><fb:like layout="<?php echo $fblayout; ?>" show_faces="<?php echo $fbface; ?>"   width="<?php echo $dbdatawidth;?>" color_scheme="<?php echo $fbcolorscheme;?>" ></fb:like>