<?php
/**
 * IDEALIAGroup srl
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.idealiagroup.com/magento-ext-license.html
 *
 * @category   IG
 * @package    IG_FloatingMenu
 * @copyright  Copyright (c) 2011-2012 IDEALIAGroup srl (http://www.idealiagroup.com)
 * @license    http://www.idealiagroup.com/magento-ext-license.html
 */
?>
<div id="ig-floatingmenu-container" class="header">
	<div class="ig-floatingmenu-wrapper">
		<div id="ig-floatingmenu-quick"></div>
		<div id="ig-floatingmenu-search"></div>
		
		<div style="clear:both"></div>
		<div id="ig-floatingmenu-nav"></div>
	</div>
</div>
<script type="text/javascript">igFloatingMenuStart()</script>